### ISSUE TITLE
Include a flag for resolving northern and southern surveys

### ISSUE THREAD

**Issue by segasai** [legacysurvey/legacysurvey#107] opened 2019-12-06 02:49 UTC
Hi, 

I don't think it is really a bug, more of the question/feature request. While ingesting the north and the south data in the same SQL table, I noticed that the sources in the stripe of the overlap between Mzls/BASS with DECAM are not removed by brick_primary key (which was my expectation). 

Is there a standard/recommended way of removing those duplicates ?
Is this it ((release=8001 and dec>32.375) or ( release=8000 and dec<32.375)) ? 

From a user perspective, It would be nice if either this selection was ANDed with the  brick_primary column or put in a separate column or maybe communicated more clearly somewhere. (it took me to figure this out + I don't know if the magic number 32.375 is stable).

Thanks,  
      Sergey

**Comment by dstndstn** [comment] 2019-12-06 11:55
Hi Sergey,

This is a good suggestion!  brick_primary is only used to resolve the overlap between adjacent bricks, not between the northern and southern surveys.  Adding a new field is a good idea.  The number 32.375 is mentioned a few times on legacysurvey.org/dr8, but we never really give a recipe for resolving the two surveys.  For the North Galactic Cap, we use 32.375, and then for the South Galactic Cap, we just use the Galactic plane as the boundary -- there is some SGC data from DECam that extends a little above 32.375.  In the DESI project, we have taken the view that this resolve step is part of targeting, not part of the imaging surveys, but it's good to remember the rest of the world!!
cheers,
--dustin

**Comment by dstndstn** [comment] 2019-12-06 11:56
I'm going to re-name the ticket to reflect your reasonable request!

**Comment by dstndstn** [comment] 2019-12-06 11:57
(ps, part of the reason we didn't do this for DR8 was that we weren't certain that the 32.375 line was the final answer)

**Comment by geordie666** [comment] 2019-12-06 13:59
For the record, the current official "resolve" function is here:

https://github.com/desihub/desitarget/blob/cd18fb52147b8a29222c425d172f44074d1904eb/py/desitarget/targets.py#L560-L612

**Comment by geordie666** [comment] 2019-12-06 14:06
Note, too, that including a flag for resolving the northern and southern imaging directly in the imaging files is a philosophical shift, as we'd decided to leave this as a targeting step.

I don't object to this request, but it does run the risk that the resolve in the imaging could become divorced from the resolve in targeting. Say, for instance, we finish DR9, and then targeting folks decide to use a different Dec cut than 32.375, or to vary that Dec cut. Then we'd have a situation where the information in the new imaging "resolve column" differed from how the targets were actually resolved.

I need to maintain the [desitarget.targets.resolve](https://github.com/desihub/desitarget/blob/cd18fb52147b8a29222c425d172f44074d1904eb/py/desitarget/targets.py#L560-L612) function, because I also have to resolve the randoms and the sky locations.

Again, none of this is objecting to the request. Just pointing out that we could end up in a situation where the imaging resolve and the targeting resolve are different.

**Comment by segasai** [comment] 2019-12-06 17:16
Thanks Adam for the resolve function and Dustin for the reply. I certainly would think that the imaging survey is in the best position to decide on the best  resolve of northern vs southern data, and DESI probably should just use what's the best from the imaging point of view (i.e. the logic probably should be inside LS processing as opposed to DESI ).
An alternative to a sharp cut in dec -- is just to split the sky on healpixels and for each healpixel make the northern/southern decision based on some statistics of number of sources (i.e. choose the survey with the largest number of sources)

**Comment by geordie666** [comment] 2019-12-06 17:49
In general, I agree that the imaging survey would be the best place to decide on the resolve.

However, given the edict that legacysurvey can't be a dependency of desitarget, there's no simple way to have the imaging surveys guide the resolve for, e.g., the desitarget randoms and blank sky locations (other than duplicating the resolve function in both repositories, which we may just have to do).

@dstndstn: Splitting on HEALPixel is another possible complication, as Data Systems enforces the use of the NESTED scheme and, historically, legacysurvey has used the RING scheme.

**Comment by dstndstn** [comment] 2019-12-06 18:02
Hi Adam,

If we put the resolve in the legacypipe code, then targeting could import and use that function...  I think we definitely don't want it in two places (Don't Repeat Yourself is an extremely important principle in this context!)

The astrometry.net code has functions to convert between nested and xy and ring indexing (yes, there are three schemes for giving numbers to cells in a rectangular grid in healpix).  The nested scheme implies a power-of-2 Nside, which I deem a silly limitation; the astrometry.net code supports arbitrary Nside (ie, arbitrary healpix cell size, within limits).

**Comment by geordie666** [comment] 2019-12-06 19:11
@dstndstn: There is a strong desire in Data Systems that legacypipe should _not_ be a dependency for desitarget. In the past, for instance, I've had to excise necessary functions from legacypipe and include them as static functions in desitarget (as I recall, we changed the license on either legacypipe or astrometry.net to facilitate this). So, we already have some duplication.

So, again, I suspect that _if_ we provide the resolve as part of legacypipe, we will have to have two different (or copied) resolve functions in the two different packages. I agree that, in general, this is a Very Bad Thing, which, to some extent, was why I commented in this ticket. Of course, legacypipe could choose to have desitarget as a dependency!

As to HEALPix, the issue isn't converting between the schemes (which is, of course, easy) it's that desitarget would use the NESTED scheme in any resolve function by default, and legacypipe would using the RING scheme. So,  it's more the risk of confusion. For this reason, I'd steer clear of any mapping from how the surveys are resolved to HEALPixel number, and stay with the Dec/Brick cuts.

**Comment by dstndstn** [comment] 2019-12-06 19:15
Yeah, actually, having desitarget as a dependency of legacypipe to pick up
this one function is not such a bad idea.

Also, the healpix cell boundaries are diagonal in RA,Dec, so they make a
really poor pixelization for our cut.

**Comment by geordie666** [comment] 2019-12-06 19:26
If making desitarget a dependency of legacypipe works for you, then I have no issue with that solution. It would certainly make my life easier!

**Comment by weaverba137** [comment] 2020-10-22 19:55
@dstndstn, did you in fact make desitarget a dependency of legacypipe, and therefore this can be closed?

**Comment by dstndstn** [comment] 2020-10-22 19:58
Hi Ben,
No, not yet, but thanks for the reminder that this would be the right way to add the hemisphere flag to, eg, the brick summary files.

**Comment by weaverba137** [comment] 2020-10-22 19:59
OK, no worries, just checking.

**Comment by geordie666** [comment] 2021-01-12 18:55
@dstndstn: When I was reviewing the documentation, it seemed like you'd added this information in the `north`/`south` survey bricks files (as the `survey_primary` column). If so, can we close this issue?

**Comment by dstndstn** [comment] 2021-01-12 19:40
Yes!

**Closed by dstndstn** 2021-01-12 19:40 UTC

**Comment by segasai** [comment] 2021-01-12 20:34
Just checking the actual DR9 files. At least in tractor bricks like these ones north_tractor/tractor/000/tractor-0008m002.fits  I don't see a survey_primary column, so it looks like with the catalogs alone you can't still get the primary/secondary info, am I correct ?

**Comment by dstndstn** [comment] 2021-01-12 20:36
That's right, it's only in the survey-bricks-<hemisphere> summary files.

**Comment by dstndstn** [comment] 2021-01-12 20:36
I think it's expected that many users will use the 'sweeps' files, which get resolved to primary

**Comment by segasai** [comment] 2021-01-12 20:39
Okay, thanks. Maybe I'll switch to sweeps as well. The full tractor catalogs are quite heavy in the database.
